#!/usr/bin/env python3
"""
Script to add descriptions to all games in the manifest.
Run this with: python3 add-game-descriptions.py
"""

import json

# Read the manifest
with open('public/games-html-files-manifest.json', 'r', encoding='utf-8') as f:
    games = json.load(f)

# Game descriptions
descriptions = {
    "A Bite at Freddy's": "Survive the night shift at a haunted pizzeria filled with animatronic horrors in this bite-sized FNAF fan game.",
    "A Difficult Game About Climbing": "Rage-inducing physics-based climbing game where a single mistake sends you plummeting back down. Inspired by Getting Over It.",
    "Amanda the Adventurer": "A horror game disguised as a children's cartoon. Watch VHS tapes of Amanda and uncover disturbing secrets.",
    "Backrooms": "Endless maze of yellow rooms, fluorescent lights, and damp carpet. Escape the liminal horror of the Backrooms.",
    "Baldi's Basics Classic Remastered": "The original math-horror game remastered! Solve Baldi's notebooks and escape the school before he catches you.",
    "Baldi's Basics Plus": "Expanded version of the cult classic horror game with more characters, items, and randomized levels.",
    "Baldi's Basics": "Learn math with Baldi! Get a wrong answer and try to escape the school while being chased by an angry teacher with a ruler.",
    "Bendy and the Ink Machine": "Explore an abandoned animation studio filled with living ink creatures. First-person horror puzzle adventure.",
    "BitLife": "Text-based life simulator where you make choices from birth to death. Live your best (or worst) virtual life!",
    "Buckshot Roulette": "Russian roulette meets tabletop horror. Use items strategically and pray the chamber is empty.",
    "Cookie Clicker": "The original idle game! Click cookies, buy upgrades, and build a cookie empire. Insanely addictive.",
    "Crazy Cattle 3D": "Drive a tractor and herd cattle in this chaotic 3D farming simulator. Don't let any escape!",
    "Crazy Chicken 3D": "Catch chickens running wild across the farm in this fast-paced 3D arcade gameoman",
    "Crazy Kitty 3D": "Wrangle adorable but mischievous cats in this 3D animal collecting game. Catch them all!",
    "Crossy Road": "Why did the chicken cross the road? Hop across traffic and rivers in this addictive endless hopper.",
    "Cuphead": "Run-and-gun boss rush game inspired by 1930s cartoons. Brutally difficult with gorgeous hand-drawn animation.",
    "Do NOT Take This Cat Home": "A mysterious cat appears at your door. What could go wrong? A short horror experience about curiosity.",
    "Doom 2": "Hell on Earth - the sequel to the legendary FPS. More demons, more weapons, more carnage.",
    "Doom 3": "Horror-focused reimagining of DOOM with cutting-edge graphics. Fight demons in the dark corridors of Mars.",
    "DOOM": "The grandfather of FPS games. Rip and tear through hordes of demons from Hell on Mars.",
    "Dumb Ways to Die": "Avoid the most ridiculous deaths possible in this darkly humorous mini-game collection.",
    "Elastic Man": "Stretch, pull, and distort a surprisingly realistic 3D face. Oddly satisfying physics simulation.",
    "Endoparasitic 2": "First-person body horror shooter where you crawl with one arm and shoot with the other.",
    "Endoparasitic": "Visceral horror shooter where an alien parasite has destroyed your legs. Crawl to survive.",
    "Five Nights at Candy's 2": "Survive against animatronic terrors in this FNAF fan game sequel with unique mechanics.",
    "Five Nights at Candy's": "Night shift at Candy's Burger and Fries. Watch the cameras and survive until 6 AM.",
    "Five Nights at Epstein's": "Controversial FNAF fan game. Survive the night in an abandoned facility.",
    "Five Nights at Freddy's 2": "More animatronics, no doors, and a Freddy Fazbear head mask. The sequel raises the stakes!",
    "Five Nights at Freddy's 3": "30 years after Freddy Fazbear's closed. One animatronic remains in the horror attraction.",
    "Five Nights at Freddy's 4": "Trapped in your childhood bedroom. Listen carefully - the monsters are at your door.",
    "Five Nights at Freddy's 4_ Halloween": "Halloween Edition featuring new nightmare animatronics and pumpkin decorations.",
    "Five Nights at Freddy's": "The indie horror phenomenon! Monitor security cameras and survive five nights at Freddy Fazbear's Pizza.",
    "Five Nights at Freddy's_ Pizza Simulator": "Build and manage your own pizzeria, now with murderous animatronics! Business simulator meets horror.",
    "Five Nights at Freddy's_ Sister Location": "Underground facility, Circus Baby's Pizza World. Voice acting and new gameplay mechanics.",
    "Five Nights at Freddy's_ Ultimate Custom Night": "50 animatronics, infinite combinations. Create your ultimate FNAF nightmare challenge.",
    "Five Nights at Freddy's_ World Refreshed": "RPG adventure in the FNAF universe with party-based battles and character collection.",
    "Five Nights at Freddy's_ World": "Turn-based RPG featuring cute versions of FNAF characters in a colorful adventure.",
    "Five Nights at Winston's": "FNAF fan game with original characters and mechanics. Survive Winston's entertainment venue.",
    "FNF vs Bob v2.0 (Bob's Onslaught)": "Friday Night Funkin mod featuring Bob in increasingly intense rap battles and glitchy horror.",
    "FNF vs Pibby Corrupted": "Battle corrupted cartoon characters in this FNF mod inspired by Come Learn With Pibby!",
    "FNF Vs. Hypno's Lullaby v2": "Pokemon creepypasta meets rhythm game. Face Hypno and other disturbing Pokemon in rap battles.",
    "Fork n Sausage": "Physics puzzle game where you impale sausages with forks. Satisfying and oddly addictive!",
    "Friday Night Funkin vs Carol V2": "Rap battle against Carol, the tsundere with killer tracks. Popular FNF character mod.",
    "Friday Night Funkin VS Impostor v4": "Among Us meets FNF! Battle against crewmates and impostors in epic rap battles.",
    "Friday Night Funkin vs Nonsense": "Face off against Nonsense, a fast-talking opponent with challenging chart patterns.",
    "Friday Night Funkin vs Shaggy": "Shaggy uses 0.001% of his power to challenge you. Notoriously difficult FNF mod.",
    "Friday Night Funkin": "Rhythm game where you rap battle opponents to win your girlfriend's heart. Catchy music and arrow keys!",
    "Fruit Ninja": "Slice fruit, avoid bombs! Swipe your way to high scores in this classic mobile arcade game.",
    "Geometry Dash Lite (REMAKE)": "Rhythm-based platformer where you jump and fly to the beat. Incredibly challenging!",
    "Getting Over It with Bennett Foddy": "Climb a mountain with a hammer in a pot. Fall, rage, and try again. Philosophical rage game.",
    "Granny 2": "Escape from Granny AND Grandpa's house. Two enemies, darker atmosphere, more terror.",
    "Granny 3": "The horror continues! Now you're on Granny's boat. Escape before they catch you in this survival horror.",
    "Granny": "Trapped in Granny's house for 5 days. Stay quiet, hide, and find a way to escape the horror.",
    "Half Life": "Gordon Freeman's crowbar-swinging adventure through Black Mesa. Revolutionary FPS that changed gaming.",
    "Half Life_ Opposing Force": "Play as Adrian Shephard, a Marine sent to clean up Black Mesa. Expansion pack with new weapons.",
    "Happy Wheels": "Ragdoll physics platformer with hilariously brutal deaths. User-created levels full of traps and gore.",
    "Hill Climb Racing Lite": "Physics-based driving game where you climb hills without flipping your vehicle. Simple but addictive!",
    "Hollow Knight": "Metroidvania masterpiece set in a vast underground kingdom. Explore, fight, and uncover dark secrets.",
    "Iron Lung": "Claustrophobic horror in a submarine with no windows. Navigate by static images in a blood ocean.",
    "Learn to Fly 2": "Help the penguin achieve his dream of flight! Launch, upgrade, and use payloads to soar.",
    "Learn to Fly 3": "The penguin's ultimate flying adventure with new vehicles, experiments, and even space travel!",
    "Learn to Fly Idle": "Idle/incremental version where your penguin flies automatically. Upgrade and watch progress!",
    "Learn to Fly": "A penguin tired of flightless jokes builds a catapult. Help him learn to fly in this physics game!",
    "Melon Playground": "Ragdoll physics sandbox where you experiment with melons and weapons. Creative destruction!",
    "Midnight Shift": "Night shift at a gas station gets creepy. Survival horror with retro PS1-style graphics.",
    "Moto X3M 2": "Perform insane stunts on a motorbike through obstacle-filled racing levels. Fast-paced sequel!",
    "Moto X3M 3": "More extreme motorcycle racing with flips, explosions, and deadly obstacles. Third installment!",
    "Moto X3M Pool Party": "Summer-themed motorcycle stunt racing with water slides, pools, and beach obstacles.",
    "Moto X3M Spooky": "Halloween edition with spooky levels, jack-o-lanterns, and haunted obstacles.",
    "Moto X3M Winter": "Winter wonderland motorcycle racing with snow, ice, and festive Christmas obstacles.",
    "Moto X3M": "Insane motorbike stunt racing! Perform backflips and reach the finish line as fast as possible.",
    "OvO 2": "Precision platformer sequel with even trickier parkour and speed-running challenges.",
    "OvO 3 Dimensions": "The parkour platformer goes 3D! Master new movement mechanics in three dimensions.",
    "OvO": "Fast-paced parkour platformer where you wall-jump, slide, and dash through challenging levels.",
    "Paper.io 2": "Capture territory by drawing lines and avoid rival players in this multiplayer area control game.",
    "People Playground": "Ragdoll physics sandbox simulator. Experiment with weapons, explosives, and contraptions on stick figures.",
    "Plants vs Zombies": "Tower defense classic! Plant sunflowers, peashooters, and more to defend against zombie waves.",
    "Plants vs. Zombies 2 Gardenless": "Time-traveling sequel without the energy system. More plants, zombies, and worlds!",
    "Please Dont Touch Anything": "A mysterious panel with a button. You only had one job... Point-and-click puzzle with multiple endings.",
    "R.E.P.O": "Blood-red horror about being trapped. Short atmospheric horror experience with disturbing visuals.",
    "Raft": "Ocean survival! Hook floating debris, build your raft bigger, and survive sharks in the endless sea.",
    "Resident Evil 2": "Zombie outbreak in Raccoon City. Leon and Claire's survival horror adventure in the police station.",
    "Resident Evil": "The game that defined survival horror. Mansion full of zombies, limited ammo, fixed camera angles.",
    "Retro Bowl College": "American football management sim with retro graphics. Recruit players and win championships!",
    "Retro Bowl": "Manage an American football team with retro 8-bit graphics and simple but strategic gameplay.",
    "Riddle School 2": "Phil is back for another school day full of puzzles, humor, and escape room challenges.",
    "Riddle School 3": "Third installment of Phil's escape adventures. Point-and-click humor and puzzle-solving continue!",
    "Riddle School 4": "Phil's vacation at the beach turns into another hilarious puzzle escape adventure.",
    "Riddle School 5": "Epic conclusion to the Riddle School saga! Aliens plot twists, and classic point-and-click fun.",
    "Riddle School": "Point-and-click adventure where Phil tries to escape boring school. Funny dialogue and clever puzzles.",
    "Riddle Transfer 2": "The sequel to Riddle Transfer with more alien encounters and mind-bending puzzles.",
    "Riddle Transfer": "Phil gets abducted by aliens! Escape the alien facility in this point-and-click adventure.",
    "Side Effects": "Horror game about disturbing pharmaceutical side effects. Short but unsettling experience.",
    "Slither.io": "Become the longest snake in the arena! Eat glowing orbs and trap other players.",
    "Solar Smash": "Planetary destruction simulator! Use lasers, missiles, and space weapons to destroy planets.",
    "Sonic CD": "Time-traveling Sonic adventure with past, present, and future versions of each level.",
    "Sonic Mania": "Classic 2D Sonic with new levels and remixed classics. Made by fans, for fans.",
    "Sonic the Hedgehog 2_ Community's Cut": "Fan-improved version of Sonic 2 with bug fixes and quality-of-life enhancements.",
    "Sonic the Hedgehog 3_ Angel Island Remastered": "Fan remaster of Sonic 3 with improved graphics and widescreen support.",
    "Sonic.EXE (ORIGINAL)": "The original creepypasta horror game. Sonic's world turned into a nightmare.",
    "Sonic.EXE": "Run from the demonic version of Sonic in this horror game based on the internet legend.",
    "Stickman Hook": "Swing through levels like Spider-Man! Tap to hook and launch yourself forward.",
    "Super Mario 63": "Fan-made Flash game combining elements from multiple Mario games, especially Mario 64.",
    "Super Mario 64": "The 3D platformer that revolutionized gaming! Collect stars in Peach's castle worlds.",
    "Super Mario Bros. Remastered": "The classic side-scroller remastered with improved graphics and smooth controls.",
    "Super Mario Bros": "The game that saved the industry! Jump, stomp Goombas, and rescue Princess Peach.",
    "Super Smash Flash": "Flash fighting game featuring characters from anime, games, and cartoons. Like Smash Bros!",
    "Super Star Car": "Drive through obstacle courses collecting stars in this fast-paced arcade racer.",
    "Superhot": "Time moves when you move. Strategic first-person shooter where you dodge bullets in slow motion.",
    "Survivor.io": "Roguelike survival game where you fight endless waves of monsters. Level up and get stronger!",
    "Temple Run 2": "Endless runner sequel with new obstacles, power-ups, and beautiful environments. Swipe to survive!",
    "Terraria": "2D crafting sandbox with mining, building, and epic boss battles. Like 2D Minecraft meets Metroidvania.",
    "Tetris": "The most addictive puzzle game ever made. Clear lines by completing rows with falling blocks.",
    "That's Not My Neighbor": "Papers Please meets horror! Check IDs and identify doppelgangers trying to infiltrate your building.",
    "The Man In The Window": "Short horror game about a mysterious figure watching from the window across the street.",
    "Traffic Racer": "Endless driving game where you weave through traffic at high speeds to earn points.",
    "Traffic Rider": "First-person motorcycle racing through traffic. Speed between cars for extra points!",
    "ULTRAKILL": "Fast-paced retro FPS where blood is fuel. Style matters and brutality is rewarded. Doom meets Devil May Cry.",
    "Undertale Yellow": "Fan prequel to Undertale following the yellow soul's journey through the underground. Incredible mod!",
    "Undertale_ Last Breath": "UNDERTALE fan game where you fight Sans in an even harder battle. Prepare to die. A lot.",
    "UNDERWHEELS": "Monster trucks meet underground racing! Crush competitors in this vehicular combat racer.",
    "Untitled Goose Game": "Be a horrible goose and ruin everyone's day in an English village. Honk!",
    "Vex 1": "Stickman parkour platformer with deadly traps. Precision timing required!",
    "Vex 2": "More challenging stickman parkour with new obstacles and acts to conquer.",
    "Vex 3 XMAS": "Holiday edition of Vex 3 with Christmas-themed levels and decorations.",
    "Vex 3": "Third installment of stickman platforming mayhem. Wall-climb and dodge sawblades!",
    "Vex 4": "Vex gets even harder! New acts, new traps, same precision platforming.",
    "Vex 5": "More acts, more challenges! The stickman parkour series continues with brutal difficulty.",
    "Vex 6": "Latest in the Vex series with fresh levels and creative obstacles to overcome.",
    "Vex 7": "Vex returns with even more parkour platforming action and death traps.",
    "Vex 8": "The newest Vex installment featuring cutting-edge stickman parkour challenges!",
    "Vex Challenges": "Time trial mode for Vex! Complete parkour challenges as fast as possible.",
    "Vex X3M 2": "Vex meets motorbike racing! Perform stunts on a bike through obstacle courses.",
    "Vex X3M": "Stickman parkour meets Moto X3M! Bike stunts with Vex-style precision required.",
    "voxels": "3D voxel world builder. Create blocky art and structures in this sandbox.",
    "VS Rewrite_ ROUND 2": "Sonic.EXE FNF mod featuring Rewrite with intense musical showdowns.",
    "We Become What We Behold": "Short but powerful game about social media, news cycles, and tribalism. Thought-provoking.",
    "Wheely 2": "Puzzle game where you help a cute car reach his goal by solving environmental puzzles.",
    "Wheely 3": "Wheely's adventures continue with more brain-teasing car puzzles!",
    "Wheely 4": "The little red car faces new challenges and puzzles in this point-and-click sequel.",
    "Wheely 5": "Wheely goes on vacation! Solve puzzles to help him enjoy his tropical getaway.",
    "Wheely 6": "Fairytale-themed puzzles as Wheely goes on a medieval adventure!",
    "Wheely 7": "Detective Wheely solves mysteries in this puzzle-solving car adventure.",
    "Wheely 8": "Wheely becomes an action movie star! Help him complete stunts and overcome obstacles.",
    "Wheely": "The original puzzle game starring an adorable red car overcoming obstacles.",
    "Wordle": "Guess the five-letter word in six tries. Viral daily word puzzle game."
}

# Update games with descriptions
for game in games:
    title = game['title']
    if title in descriptions:
        game['description'] = descriptions[title]
    else:
        game['description'] = f"Experience {title}, an exciting browser-based game with unique gameplay and challenges."

# Write updated manifest
with open('public/games-html-files-manifest.json', 'w', encoding='utf-8') as f:
    json.dump(games, f, indent=2, ensure_ascii=False)

print(f"✅ Updated {len(games)} games with descriptions!")
print(f"📝 Games with custom descriptions: {sum(1 for g in games if g['title'] in descriptions)}")
print(f"🎮 Total games: {len(games)}")
