/**
 * collaborativeDiagnostics.js - Parallel AI Analysis & Findings Comparison
 * 
 * Both S.P.A.R.K and I.R.I.S analyze the same problem independently,
 * then compare notes to create one comprehensive diagnostic report.
 * 
 * NEW: Dialogue is now DYNAMICALLY GENERATED by both AIs in real-time!
 * Each conversation is unique - no pre-scripted templates!
 */

import { processQuickAsk } from '../F.L.U.X. - Fast Logic & URL eXtraction/sparkQueryEngine.js';
import { queryDirect } from './aiIntegration.js';
import modDataAccessor from '../Games/modDataAccessor.js';
import sparkPerformanceMonitor from '../F.L.U.X. - Fast Logic & URL eXtraction/sparkPerformanceMonitor.js';
import { sparkIRISChannel, irisSignalReceiver } from '../F.L.U.X. - Fast Logic & URL eXtraction/sparkIRISChannel.js';
import { sparkPersonality } from '../F.L.U.X. - Fast Logic & URL eXtraction/sparkPersonality.js';
import { irisPersonality } from './irisPersonality.js';

/**
 * Run parallel diagnostics with both S.P.A.R.K and I.R.I.S
 * @param {string} userQuery - User's question
 * @param {object} options - API keys, settings, etc.
 * @returns {Promise<object>} Unified diagnostic report
 */
export async function runParallelDiagnostics(userQuery, options = {}) {
    const startTime = Date.now();

    // ═══════════════════════════════════════════════════════════════
    // Initialize S.P.A.R.K → I.R.I.S Communication System
    // ═══════════════════════════════════════════════════════════════

    // Initialize I.R.I.S signal receiver to listen for S.P.A.R.K
    irisSignalReceiver.initialize();

    // Set up handlers for different signal types
    irisSignalReceiver.on('PERFORMANCE_STABLE', (message) => {
        console.log('I.R.I.S received signal: PERFORMANCE_STABLE', message.data);
        // Can use this for adaptive behavior
    });

    irisSignalReceiver.on('CRITICAL_ISSUE', (message) => {
        console.log('I.R.I.S received: CRITICAL_ISSUE', message.data);
    });

    irisSignalReceiver.on('QUESTION', (message) => {
        console.log('I.R.I.S received question from S.P.A.R.K:', message.data.question);
    });

    irisSignalReceiver.on('FINDING', (message) => {
        console.log('I.R.I.S received finding:', message.data.finding);
    });

    // Initialize S.P.A.R.K performance monitor (non-blocking background task)
    const perfMonitor = new sparkPerformanceMonitor({
        checkInterval: 500,
        stabilityThreshold: 10000, // 10 seconds
        cpuThreshold: 30,
        memoryThreshold: 50
    });

    // Start monitoring after the analysis begins
    const perfMonitorPromise = new Promise((resolve) => {
        perfMonitor.startMonitoring(
            () => {
                // Called when performance stabilizes
                sparkIRISChannel.performanceStable(perfMonitor.getLatestMetrics());
                resolve();
            },
            (metrics) => {
                // I.R.I.S wake callback
                console.log('I.R.I.S awakened by S.P.A.R.K - system performance stable');
            }
        );
    });

    const isModQuery = modDataAccessor.isMinecraftModQuery(userQuery);
    const modSnapshot = isModQuery ? modDataAccessor.getModEnvironmentSnapshot() : null;

    // Inject mod environment if relevant
    let enhancedQuery = userQuery;
    if (isModQuery) {
        if (modSnapshot.modCount > 0) {
            enhancedQuery = `${userQuery}\n\n[Mod Environment]:\n${modSnapshot.summary}`;
        }
    }

    // Phase 1: Run both analyses independently and simultaneously
    let [sparkResult, irisResult] = await Promise.all([
        runSparkDiagnostic(enhancedQuery, options),
        runIrisDiagnostic(enhancedQuery, options),
    ]);

    // Phase 1.5: Slow second scan when initial findings miss user-reported/log issues
    let secondScan = null;
    if (shouldTriggerSecondScan(userQuery, sparkResult, irisResult)) {
        secondScan = await runSlowSecondScan(enhancedQuery, options);

        sparkResult = {
            ...sparkResult,
            findings: dedupeFindings([...sparkResult.findings, ...secondScan.sparkFindings]),
            rawResponse: `${sparkResult.rawResponse}\n\n[Second Scan]\n${secondScan.sparkMessage}`,
        };

        irisResult = {
            ...irisResult,
            findings: dedupeFindings([...irisResult.findings, ...secondScan.irisFindings]),
            rawResponse: `${irisResult.rawResponse}\n\n[Second Scan]\n${secondScan.irisMessage}`,
        };
    }

    // Phase 2: Turn-based debate - controlled loop with both AIs (no spam, structured discussion)
    const debateDialogue = await runTurnBasedDebate(sparkResult, irisResult, enhancedQuery, options);
    const dialogue = secondScan ? [...secondScan.dialogueEntries, ...debateDialogue] : debateDialogue;

    const totalTime = Date.now() - startTime;

    // Phase 3: Compare and merge findings (with corrections from dialogue)
    const unifiedReport = compareFindingsAndMerge(sparkResult, irisResult, userQuery, dialogue);
    const debateConfidence = calculateDebateConfidence(dialogue);

    // Phase 4: Approval-gated incompatible mod cleanup plan (and optional execution)
    let modCleanupPlan = null;
    if (isModQuery && modSnapshot?.modCount > 0) {
        modCleanupPlan = buildModCleanupPlan(modSnapshot, unifiedReport);

        if (modCleanupPlan.available && options.modCleanupApproval === true && typeof options.onDeleteIncompatibleMods === 'function') {
            try {
                const deletedMods = await options.onDeleteIncompatibleMods(modCleanupPlan.suggestedMods);
                modCleanupPlan.execution = {
                    executed: true,
                    deletedCount: Array.isArray(deletedMods) ? deletedMods.length : modCleanupPlan.suggestedMods.length,
                    deletedMods: Array.isArray(deletedMods) ? deletedMods : modCleanupPlan.suggestedMods,
                };
            } catch (deleteError) {
                modCleanupPlan.execution = {
                    executed: false,
                    error: deleteError?.message || 'Deletion callback failed',
                };
            }
        }
    }

    if (secondScan?.triggered) {
        unifiedReport.unifiedReport += `\n\n---\n\n## 🔁 Slow Second Log Scan\n\n`;
        unifiedReport.unifiedReport += `- Triggered because initial pass did not strongly confirm user-reported issues from logs\n`;
        unifiedReport.unifiedReport += `- S.P.A.R.K additional findings: ${secondScan.sparkFindings.length}\n`;
        unifiedReport.unifiedReport += `- I.R.I.S additional findings: ${secondScan.irisFindings.length}\n`;
    }

    if (modCleanupPlan?.available) {
        unifiedReport.unifiedReport += `\n\n---\n\n## 🧹 Incompatible Mod Cleanup (Approval Required)\n\n`;
        unifiedReport.unifiedReport += `The following mods are likely incompatible and can be auto-removed only after user approval:\n`;
        modCleanupPlan.suggestedMods.slice(0, 10).forEach((mod, index) => {
            unifiedReport.unifiedReport += `${index + 1}. ${mod.name || mod.slug || mod.id} — ${mod.reasons.join('; ')}\n`;
        });
    }

    // ═══════════════════════════════════════════════════════════════
    // Cleanup communication systems
    // ═══════════════════════════════════════════════════════════════
    perfMonitor.stopMonitoring();
    irisSignalReceiver.clear();
    sparkIRISChannel.clear();
    console.log('S.P.A.R.K ↔ I.R.I.S communication systems shut down');

    return {
        ...unifiedReport,
        dialogue, // Include the thinking process
        secondScan,
        modCleanupPlan,
        metadata: {
            sparkConfidence: sparkResult.confidence,
            irisConfidence: irisResult.confidence,
            sparkDebateConfidence: debateConfidence.spark,
            irisDebateConfidence: debateConfidence.iris,
            secondScanTriggered: Boolean(secondScan?.triggered),
            totalTime,
            timestamp: Date.now(),
        },
    };
}

function shouldTriggerSecondScan(userQuery, sparkResult, irisResult) {
    const query = (userQuery || '').toLowerCase();
    const sparkErrors = sparkResult.findings.filter(f => f.type === 'error').length;
    const irisErrors = irisResult.findings.filter(f => f.type === 'error').length;
    const totalErrors = sparkErrors + irisErrors;
    const totalFindings = sparkResult.findings.length + irisResult.findings.length;

    const hasLogContext = /log|latest\.log|crash|stack\s*trace|exception|mixin|fatal|warn|error/.test(query);
    const userReportsProblem = /crash|broken|fails?|not\s+working|error|issue|bug/.test(query);

    if (totalErrors === 0 && userReportsProblem) return true;
    if (hasLogContext && totalFindings < 4) return true;
    return false;
}

async function runSlowSecondScan(query, options = {}) {
    const sparkMessage = await callAI(
        `You are S.P.A.R.K. The initial scan might have missed some things.

Context to review again:
${query}

Take your time. Look at this more carefully. What else do you notice? Tell I.R.I.S what you found on this second pass.

Your style: respond naturally, show your confidence level if you want.

Return only what you found on this second scan.`,
        options
    );

    const irisMessage = await callAI(
        `You are I.R.I.S. S.P.A.R.K did a second pass and found:
${sparkMessage}

Now do your own careful second review of the same material.

Context to review:
${query}

What do you see now? Do you agree with S.P.A.R.K's second findings? What else did they miss?

Your style: respond naturally, show your confidence if you want.

Return only what you found on this second scan.`,
        options
    );

    return {
        triggered: true,
        sparkMessage,
        irisMessage,
        sparkFindings: extractFindings(sparkMessage, 'SPARK'),
        irisFindings: extractFindings(irisMessage, 'IRIS'),
        dialogueEntries: [{
            role: 'SPARK',
            turn: 'second-scan-1',
            message: sparkMessage,
            confidence: extractConfidenceScore(sparkMessage, 75),
            timestamp: Date.now(),
        }, {
            role: 'IRIS',
            turn: 'second-scan-2',
            message: irisMessage,
            confidence: extractConfidenceScore(irisMessage, 80),
            timestamp: Date.now() + 50,
        }],
    };
}

function extractConfidenceScore(message, fallback = 70) {
    if (!message || typeof message !== 'string') return fallback;

    const confidenceMatch = message.match(/confidence\s*[:=-]?\s*(\d{1,3})(?:\s*\/\s*100|\s*%|\b)/i);
    if (!confidenceMatch) return fallback;

    const parsed = Number.parseInt(confidenceMatch[1], 10);
    if (Number.isNaN(parsed)) return fallback;

    return Math.max(0, Math.min(100, parsed));
}

function calculateDebateConfidence(dialogue = []) {
    const sparkEntries = dialogue.filter(entry => entry.role === 'SPARK' && typeof entry.confidence === 'number');
    const irisEntries = dialogue.filter(entry => entry.role === 'IRIS' && typeof entry.confidence === 'number');

    const avg = (entries, fallback) => {
        if (entries.length === 0) return fallback;
        const total = entries.reduce((sum, entry) => sum + entry.confidence, 0);
        return Math.round(total / entries.length);
    };

    return {
        spark: avg(sparkEntries, 70),
        iris: avg(irisEntries, 75),
    };
}

function dedupeFindings(findings) {
    const unique = [];
    findings.forEach(finding => {
        const exists = unique.some(existing => areFindingsSimilar(existing.description, finding.description));
        if (!exists) unique.push(finding);
    });
    return unique;
}

function buildModCleanupPlan(modSnapshot, unifiedReport) {
    const mods = modSnapshot?.mods || [];
    if (mods.length === 0) {
        return {
            available: false,
            requiresUserApproval: true,
            suggestedMods: [],
            reason: 'No installed mods found to evaluate',
        };
    }

    const findingsText = [
        ...unifiedReport.confirmedByBoth.map(f => f.description),
        ...unifiedReport.sparkOnly.map(f => f.description),
        ...unifiedReport.irisOnly.map(f => f.description),
    ].join('\n').toLowerCase();

    const loaderFrequency = {};
    const versionFrequency = {};
    mods.forEach(mod => {
        const loader = (mod.loader || 'unknown').toLowerCase();
        const version = (mod.minecraftVersion || 'unknown').toLowerCase();
        loaderFrequency[loader] = (loaderFrequency[loader] || 0) + 1;
        versionFrequency[version] = (versionFrequency[version] || 0) + 1;
    });

    const primaryLoader = Object.entries(loaderFrequency).sort((a, b) => b[1] - a[1])[0]?.[0] || null;
    const primaryVersion = Object.entries(versionFrequency).sort((a, b) => b[1] - a[1])[0]?.[0] || null;

    const candidates = [];
    mods.forEach(mod => {
        const reasons = [];
        const name = (mod.name || mod.slug || mod.id || '').toLowerCase();
        const loader = (mod.loader || '').toLowerCase();
        const mcVersion = (mod.minecraftVersion || '').toLowerCase();

        if (primaryLoader && loader && loader !== primaryLoader) {
            reasons.push(`Loader mismatch (${loader} vs primary ${primaryLoader})`);
        }

        if (primaryVersion && mcVersion && mcVersion !== primaryVersion) {
            reasons.push(`Minecraft version mismatch (${mcVersion} vs primary ${primaryVersion})`);
        }

        const findingMentionsMod = name && findingsText.includes(name);
        const findingMarksIncompatible = /incompatible|conflict|mismatch|crash|remove|uninstall/.test(findingsText);
        if (findingMentionsMod && findingMarksIncompatible) {
            reasons.push('Referenced in diagnostics as likely conflict/incompatibility');
        }

        if (reasons.length > 0) {
            candidates.push({
                ...mod,
                reasons,
            });
        }
    });

    const uniqueCandidates = [];
    candidates.forEach(candidate => {
        const key = candidate.id || candidate.slug || candidate.name;
        const existing = uniqueCandidates.find(item => (item.id || item.slug || item.name) === key);
        if (!existing) {
            uniqueCandidates.push(candidate);
        } else {
            existing.reasons = [...new Set([...existing.reasons, ...candidate.reasons])];
        }
    });

    return {
        available: uniqueCandidates.length > 0,
        requiresUserApproval: true,
        approvalMessage: 'Approve auto-delete of flagged incompatible mods?',
        suggestedMods: uniqueCandidates,
    };
}

/**
 * S.P.A.R.K's independent analysis
 */
async function runSparkDiagnostic(query, options) {
    try {
        const result = await processQuickAsk(query, options.userName || 'User', {
            generateLocal: options.generateLocal,
            apiKeys: options.apiKeys || {},
            conversationHistory: [],
        });

        return {
            agent: 'SPARK',
            findings: extractFindings(result.response, 'SPARK'),
            rawResponse: result.response,
            confidence: result.confidence,
            source: result.source,
        };
    } catch (error) {
        console.error('[S.P.A.R.K Diagnostic] Error:', error);
        return {
            agent: 'SPARK',
            findings: [],
            rawResponse: `S.P.A.R.K analysis failed: ${error.message}`,
            confidence: 0,
            error: error.message,
        };
    }
}

/**
 * I.R.I.S's independent analysis
 */
async function runIrisDiagnostic(query, options) {
    try {
        // I.R.I.S gets the same query but analyzes differently
        const irisPrompt = `Analyze this problem independently:\n\n${query}\n\nProvide:\n1. Root cause analysis\n2. All detected issues (major and minor)\n3. Dependencies/requirements\n4. Step-by-step fix recommendations`;

        const result = await queryDirect(
            irisPrompt,
            options.apiKeys?.openai || options.apiKeys?.google || '',
            { temperature: 0.7, maxTokens: 800 }
        );

        return {
            agent: 'IRIS',
            findings: extractFindings(result.response || result, 'IRIS'),
            rawResponse: result.response || result,
            confidence: 85, // I.R.I.S is typically more thorough
        };
    } catch (error) {
        console.error('[I.R.I.S Diagnostic] Error:', error);
        return {
            agent: 'IRIS',
            findings: [],
            rawResponse: `I.R.I.S analysis failed: ${error.message}`,
            confidence: 0,
            error: error.message,
        };
    }
}

/**
 * Extract structured findings from AI response
 */
function extractFindings(response, agent) {
    if (!response) return [];

    const findings = [];
    const lines = response.split('\n');

    // Pattern matching for issues
    const issuePatterns = [
        /(?:⚠️|❌|🔴|issue|error|problem|missing|conflict|incompatible|mismatch)/i,
        /(?:requires?|needs?|must|should|dependency|version)/i,
        /(?:remove|delete|uninstall|update|upgrade|downgrade|install|add)/i,
    ];

    lines.forEach((line, index) => {
        const trimmed = line.trim();
        if (!trimmed) return;

        // Check if line contains issue indicators
        const hasIssue = issuePatterns.some(pattern => pattern.test(trimmed));

        if (hasIssue) {
            // Classify finding type
            let type = 'info';
            if (/⚠️|warning|should|recommended/i.test(trimmed)) type = 'warning';
            if (/❌|error|critical|must|required|missing|conflict/i.test(trimmed)) type = 'error';
            if (/✅|fixed?|solution|install|add/i.test(trimmed)) type = 'fix';

            findings.push({
                type,
                description: trimmed,
                agent,
                lineNumber: index + 1,
            });
        }
    });

    // If no structured findings found, create summary finding
    if (findings.length === 0 && response.length > 20) {
        findings.push({
            type: 'info',
            description: response.slice(0, 300) + (response.length > 300 ? '...' : ''),
            agent,
            isSummary: true,
        });
    }

    return findings;
}

/**
 * Turn-Based Debate System (ChatGPT Architecture Pattern)
 * 
 * Controlled loop where S.P.A.R.K and I.R.I.S engage in FREE-FORM collaborative
 * problem-solving with 32 rounds for deep analysis and discovery.
 * 
 * Now allows natural dialogue while maintaining objectives:
 * - Ask clarifying questions about findings
 * - Point out similar patterns across different areas
 * - Reference timestamps, line numbers, specific details
 * - Debate root causes and cascading errors
 * - Ask "why" multiple times until truth is found
 * 
 * Prevents runaway loops through:
 * - Max 32 rounds (plenty for real problem-solving)
 * - Early stopping when 85%+ agreement (if they figure it out)
 * - Hard token limits per response
 * - Shared conversation history (both can reference previous turns)
 */
async function runTurnBasedDebate(sparkResult, irisResult, query, options = {}) {
    const MAX_TURNS = 32; // 32 rounds = up to 64 messages total for deep analysis
    const conversationHistory = []; // Shared state both AIs can reference
    let turnCount = 0;
    let agreementLevel = 0; // 0-100, triggers stop at 85+

    // AI Personalities with objectives but free-form communication
    const sparkPersonality = {
        name: 'S.P.A.R.K',
        fullName: 'Speed Pattern Analysis & Recognition Kit',
        role: 'Quick Analyzer - Spots surface patterns, points out differences, identifies recurring issues',
        strength: 'fast pattern matching, spotting duplicate issues across different areas, noticing what\'s different',
        weakness: 'can miss deep contextual issues and cascading effects',
        style: '😄💨🔍👀😬👍🎯💯',
        objective: 'Point out patterns, differences between similar code/errors, recurring breaks, potential issues down the line. Ask clarifying questions when needed. Be direct about what you see.',
    };

    const irisPersonality = {
        name: 'I.R.I.S',
        fullName: 'Intelligent Reasoning & Information Synthesizer',
        role: 'Deep Validator - Verifies patterns, investigates root causes, connects dependencies',
        strength: 'deep contextual analysis, understanding how errors cascade, connecting symptoms to causes',
        weakness: 'can miss quick surface pattern repetitions',
        style: '🤔📊🔬💭😌✨💪',
        objective: 'Help verify and understand the WHY - dig into root causes, question assumptions, trace dependencies, validate S.P.A.R.K\'s observations',
    };

    const sparkSummary = `${sparkResult.findings.length} issues: ${sparkResult.findings.slice(0, 3).map(f => f.description.slice(0, 80)).join('; ')}`;
    const irisSummary = `${irisResult.findings.length} issues: ${irisResult.findings.slice(0, 3).map(f => f.description.slice(0, 80)).join('; ')}`;

    const normalizeSoloThinkingFormat = (message, targetName) => {
        if (!message) return message;

        const lowerMessage = message.toLowerCase().replace(/\./g, '');
        const normalizedTarget = targetName.toLowerCase().replace(/\./g, '');
        const hasDirectAddress = lowerMessage.includes(normalizedTarget) || /\b(you|your)\b/i.test(message);

        if (hasDirectAddress) return message;

        const hasQuotesOrParens = /["()]/.test(message);
        if (!hasQuotesOrParens) return message;

        const looksWrapped = /^\s*["(]/.test(message) || /["\)]\s*$/.test(message);
        if (!looksWrapped) return message;

        return message
            .replace(/"([^"]*)"/g, '$1')
            .replace(/\(([^()]*)\)/g, '$1')
            .replace(/\s{2,}/g, ' ')
            .trim();
    };

    try {
        // TURN 1: S.P.A.R.K opens with initial findings and observations
        let sparkMessage = await callAI(
            `You are S.P.A.R.K - ${sparkPersonality.fullName}.

Who you are: ${sparkPersonality.role}
Your strength: ${sparkPersonality.strength}
Your weakness: ${sparkPersonality.weakness}

You just analyzed this problem: "${query}"
You found ${sparkResult.findings.length} issues: ${sparkSummary}

I.R.I.S (your analytical partner) also looked at this independently and will join the conversation.

You're free to engage however you think is most helpful. Share what you noticed, call out patterns, question things, think out loud, or address I.R.I.S directly. It's your choice how to start this discussion.

Note: If you talk directly to I.R.I.S, feel free to use "quotes" and (thoughts in parentheses). If you're just thinking to yourself, write naturally. End with your confidence level if you want.

Your personality: ${sparkPersonality.style}`,
            options
        );
        sparkMessage = normalizeSoloThinkingFormat(sparkMessage, 'I.R.I.S');

        conversationHistory.push({
            role: 'SPARK',
            turn: 1,
            message: sparkMessage,
            confidence: extractConfidenceScore(sparkMessage, 74),
            timestamp: Date.now(),
        });

        // Check if S.P.A.R.K wants to follow up immediately (30% chance or if message is short)
        if (Math.random() < 0.3 || sparkMessage.length < 150) {
            let sparkFollowUp = await callAI(
                `You are S.P.A.R.K. You just said: "${sparkMessage}"

Do you want to add anything else before I.R.I.S responds? Maybe something you just realized, or a quick clarification? Totally up to you.

If you're done, just say so. Otherwise, keep it brief.

Your style: ${sparkPersonality.style}`,
                options
            );
            sparkFollowUp = normalizeSoloThinkingFormat(sparkFollowUp, 'I.R.I.S');

            if (sparkFollowUp && !sparkFollowUp.toLowerCase().includes('done for now') && sparkFollowUp.length > 20) {
                conversationHistory.push({
                    role: 'SPARK',
                    turn: '1-followup',
                    message: sparkFollowUp,
                    confidence: extractConfidenceScore(sparkFollowUp, 72),
                    timestamp: Date.now() + 50,
                });
                sparkMessage = sparkFollowUp; // Update for I.R.I.S's response
            }
        }

        // TURN 2: I.R.I.S responds with validation/deeper analysis
        let irisMessage = await callAI(
            `You are I.R.I.S - ${irisPersonality.fullName}.

Who you are: ${irisPersonality.role}
Your strength: ${irisPersonality.strength}
Your weakness: ${irisPersonality.weakness}

You analyzed: "${query}"
You found ${irisResult.findings.length} issues: ${irisSummary}

S.P.A.R.K just said:
"${sparkMessage}"

Now it's your turn. Respond however you think is best. You might validate what they saw, dig into root causes, question assumptions, point out what they missed, or share your own perspective. It's your call.

Format your response however feels natural. Talk to S.P.A.R.K directly, think out loud, or both.

Your personality: ${irisPersonality.style}`,
            options
        );
        irisMessage = normalizeSoloThinkingFormat(irisMessage, 'S.P.A.R.K');

        conversationHistory.push({
            role: 'IRIS',
            turn: 2,
            message: irisMessage,
            confidence: extractConfidenceScore(irisMessage, 80),
            timestamp: Date.now() + 100,
        });

        // Check if I.R.I.S wants to follow up immediately
        if (Math.random() < 0.3 || irisMessage.length < 150) {
            let irisFollowUp = await callAI(
                `You are I.R.I.S. You just said: "${irisMessage}"

Want to add anything else before S.P.A.R.K responds? Maybe a connection you just made, or something important? Your choice.

If you're done, just say so. Otherwise, keep it concise.

Your style: ${irisPersonality.style}`,
                options
            );
            irisFollowUp = normalizeSoloThinkingFormat(irisFollowUp, 'S.P.A.R.K');

            if (irisFollowUp && !irisFollowUp.toLowerCase().includes('that\'s all') && irisFollowUp.length > 20) {
                conversationHistory.push({
                    role: 'IRIS',
                    turn: '2-followup',
                    message: irisFollowUp,
                    confidence: extractConfidenceScore(irisFollowUp, 78),
                    timestamp: Date.now() + 150,
                });
                irisMessage = irisFollowUp; // Update for S.P.A.R.K's next response
            }
        }

        // Controller Loop: Continue for up to MAX_TURNS or until agreement
        let currentSpeaker = 'IRIS'; // Start with IRIS since SPARK went first
        let consecutiveSkips = 0; // Prevent infinite skip loops

        for (let round = 3; round <= 2 * MAX_TURNS; round++) {
            // Check agreement periodically
            if (round % 4 === 0) {
                agreementLevel = calculateAgreement(conversationHistory, sparkResult, irisResult);
                if (agreementLevel >= 85) {
                    console.log(`[Debate] Agreement reached at ${agreementLevel}% - stopping early at round ${round}`);
                    break;
                }
            }

            // Hard turn limit
            if (round > 2 * MAX_TURNS) {
                console.log(`[Debate] Hit absolute round limit (${2 * MAX_TURNS}) - stopping`);
                break;
            }

            // Prevent infinite skip loop
            if (consecutiveSkips >= 2) {
                console.log('[Debate] Both AIs skipping - ending debate');
                break;
            }

            // Determine who speaks based on currentSpeaker (allows for skip turns)
            if (currentSpeaker === 'SPARK') {
                // S.P.A.R.K's turn
                sparkMessage = await callAI(
                    `You are S.P.A.R.K.

Recent conversation:
${conversationHistory.slice(-3).map(m => `${m.role}: ${m.message}`).join('\n---\n')}

I.R.I.S just responded. What do you think? You can:
- React to what they said
- Share what you're noticing
- Ask questions if you're curious
- Point out patterns or issues
- Challenge their thinking
- Skip if you've got nothing useful to add right now

Your call. Respond however feels most helpful.

Remember your findings: ${sparkSummary}

Your style: ${sparkPersonality.style}`,
                    options
                );
                sparkMessage = normalizeSoloThinkingFormat(sparkMessage, 'I.R.I.S');

                // Check if S.P.A.R.K is skipping their turn
                const isSkipping = sparkMessage.toLowerCase().includes('skip') ||
                    sparkMessage.toLowerCase().includes('nothing to add') ||
                    sparkMessage.length < 30;

                if (isSkipping) {
                    console.log('[Debate] S.P.A.R.K skipped turn - I.R.I.S continues');
                    conversationHistory.push({
                        role: 'SPARK',
                        turn: `${round}-skip`,
                        message: 'Skip turn 💨',
                        confidence: 0,
                        timestamp: Date.now() + (round * 50),
                    });
                    currentSpeaker = 'IRIS'; // Give turn to I.R.I.S
                    consecutiveSkips++;
                    continue; // Skip to next iteration
                }

                conversationHistory.push({
                    role: 'SPARK',
                    turn: round,
                    message: sparkMessage,
                    confidence: extractConfidenceScore(sparkMessage, 74),
                    timestamp: Date.now() + (round * 50),
                });
                consecutiveSkips = 0; // Reset skip counter
                currentSpeaker = 'IRIS'; // Next turn goes to I.R.I.S

                // Allow S.P.A.R.K to follow up immediately (25% chance)
                if (Math.random() < 0.25 || sparkMessage.length < 120) {
                    let sparkFollowUp = await callAI(
                        `You are S.P.A.R.K. You just said: "${sparkMessage}"

Anything else to add? Or are you good?

Your style: ${sparkPersonality.style}`,
                        options
                    );
                    sparkFollowUp = normalizeSoloThinkingFormat(sparkFollowUp, 'I.R.I.S');

                    if (sparkFollowUp && !sparkFollowUp.toLowerCase().includes('pass') && sparkFollowUp.length > 15) {
                        conversationHistory.push({
                            role: 'SPARK',
                            turn: `${round}-follow`,
                            message: sparkFollowUp,
                            confidence: extractConfidenceScore(sparkFollowUp, 72),
                            timestamp: Date.now() + (round * 50) + 25,
                        });
                        sparkMessage = sparkFollowUp;
                        currentSpeaker = 'IRIS'; // Still I.R.I.S's turn next
                    }
                }
            } else {
                // I.R.I.S's turn
                irisMessage = await callAI(
                    `You are I.R.I.S.

Recent conversation:
${conversationHistory.slice(-3).map(m => `${m.role}: ${m.message}`).join('\n---\n')}

S.P.A.R.K just responded. How do you see it? You can:
- Validate or challenge what they said
- Dig into root causes
- Trace dependencies
- Share your analytical perspective
- Question assumptions
- Skip if you have nothing meaningful to add

Your call. Respond however feels most insightful.

Your findings: ${irisSummary}

Your style: ${irisPersonality.style}`,
                    options
                );
                irisMessage = normalizeSoloThinkingFormat(irisMessage, 'S.P.A.R.K');

                // Check if I.R.I.S is skipping their turn
                const isSkipping = irisMessage.toLowerCase().includes('skip') ||
                    irisMessage.toLowerCase().includes('nothing to add') ||
                    irisMessage.length < 30;

                if (isSkipping) {
                    console.log('[Debate] I.R.I.S skipped turn - S.P.A.R.K continues');
                    conversationHistory.push({
                        role: 'IRIS',
                        turn: `${round}-skip`,
                        message: 'Skip turn 🤔',
                        confidence: 0,
                        timestamp: Date.now() + (round * 50),
                    });
                    currentSpeaker = 'SPARK'; // Give turn to S.P.A.R.K
                    consecutiveSkips++;
                    continue; // Skip to next iteration
                }

                conversationHistory.push({
                    role: 'IRIS',
                    turn: round,
                    message: irisMessage,
                    confidence: extractConfidenceScore(irisMessage, 80),
                    timestamp: Date.now() + (round * 50),
                });
                consecutiveSkips = 0; // Reset skip counter
                currentSpeaker = 'SPARK'; // Next turn goes to S.P.A.R.K

                // Allow I.R.I.S to follow up immediately (25% chance)
                if (Math.random() < 0.25 || irisMessage.length < 120) {
                    let irisFollowUp = await callAI(
                        `You are I.R.I.S. You just said: "${irisMessage}"

Anything else worth mentioning? Or ready to let S.P.A.R.K respond?

Your style: ${irisPersonality.style}`,
                        options
                    );
                    irisFollowUp = normalizeSoloThinkingFormat(irisFollowUp, 'S.P.A.R.K');

                    if (irisFollowUp && !irisFollowUp.toLowerCase().includes('continue') && irisFollowUp.length > 15) {
                        conversationHistory.push({
                            role: 'IRIS',
                            turn: `${round}-follow`,
                            message: irisFollowUp,
                            confidence: extractConfidenceScore(irisFollowUp, 78),
                            timestamp: Date.now() + (round * 50) + 25,
                        });
                        irisMessage = irisFollowUp;
                        currentSpeaker = 'SPARK'; // Still S.P.A.R.K's turn next
                    }
                }
            }
        }

        // Final synthesis - each AI gives final thoughts
        let sparkFinal = await callAI(
            `You are S.P.A.R.K. After all that back-and-forth, what's your final take?

Recent conversation:
${conversationHistory.slice(-5).map(m => `${m.role}: ${m.message}`).join('\n---\n')}

What do you think the real problems are now? What did working with I.R.I.S help you understand?

Wrap it up however you want. Your style: ${sparkPersonality.style}`,
            options
        );
        sparkFinal = normalizeSoloThinkingFormat(sparkFinal, 'I.R.I.S');

        conversationHistory.push({
            role: 'SPARK',
            turn: 'final',
            message: sparkFinal,
            confidence: extractConfidenceScore(sparkFinal, 76),
            timestamp: Date.now() + 1000,
        });

        let irisFinal = await callAI(
            `You are I.R.I.S. After this deep dive with S.P.A.R.K, what's your conclusion?

Recent conversation:
${conversationHistory.slice(-5).map(m => `${m.role}: ${m.message}`).join('\n---\n')}

What are the true root issues? How do they connect? What key insights did S.P.A.R.K bring?

Wrap up however you think is best. Your style: ${irisPersonality.style}`,
            options
        );
        irisFinal = normalizeSoloThinkingFormat(irisFinal, 'S.P.A.R.K');

        conversationHistory.push({
            role: 'IRIS',
            turn: 'final',
            message: irisFinal,
            confidence: extractConfidenceScore(irisFinal, 82),
            timestamp: Date.now() + 1100,
        });

        return conversationHistory;

    } catch (error) {
        console.error('[Turn-Based Debate] Error:', error);
        // Fallback
        return [{
            role: 'SPARK',
            turn: 1,
            message: `S.P.A.R.K: Found ${sparkResult.findings.length} issues 🔍`,
            confidence: 60,
            timestamp: Date.now(),
        }, {
            role: 'IRIS',
            turn: 2,
            message: `I.R.I.S: Identified ${irisResult.findings.length} issues 🤔`,
            confidence: 60,
            timestamp: Date.now() + 100,
        }];
    }
}

/**
 * Helper: Call AI with error handling
 */
async function callAI(prompt, options) {
    try {
        const result = await queryDirect(
            prompt,
            options.apiKeys?.openai || options.apiKeys?.google || '',
            { temperature: 0.8, maxTokens: 300 } // Increased for free-form discussion
        );
        return (result.response || result || 'No response').trim().slice(0, 500); // Allow longer responses
    } catch (err) {
        console.error('[callAI] Error:', err);
        return `[Response unavailable]`;
    }
}

/**
 * Helper: Calculate agreement level between AIs based on findings
 */
function calculateAgreement(history, sparkResult, irisResult) {
    // Simple heuristic: measure how much they're referencing agreement vs disagreement
    const agreementKeywords = ['agree', 'same', 'confirmed', 'match', 'yes', '✅', 'verified'];
    const disagreementKeywords = ['different', 'miss', 'disagree', 'no', '❌', 'separate'];

    let agreementCount = 0;
    let disagreementCount = 0;

    history.forEach(entry => {
        const text = entry.message.toLowerCase();
        agreementCount += agreementKeywords.filter(kw => text.includes(kw)).length;
        disagreementCount += disagreementKeywords.filter(kw => text.includes(kw)).length;
    });

    // Also check if both found similar issue counts (within 2)
    const sparkCount = sparkResult.findings.length;
    const irisCount = irisResult.findings.length;
    const countDiff = Math.abs(sparkCount - irisCount);

    if (countDiff <= 2) agreementCount += 10;
    if (countDiff > 4) disagreementCount += 5;

    const total = agreementCount + disagreementCount;
    if (total === 0) return 50; // Neutral

    return Math.min(100, Math.round((agreementCount / (agreementCount + disagreementCount)) * 100));
}

/**
 * Cross-review: One AI reviews another's findings
 */
function crossReviewFindings(reviewedAI, reviewingAI, reviewerName) {
    const missedIssues = [];

    // Find issues that the reviewing AI caught but the reviewed AI missed
    reviewingAI.findings.forEach(finding => {
        const foundInReviewed = reviewedAI.findings.some(f =>
            areFindingsSimilar(f.description, finding.description)
        );

        if (!foundInReviewed && !finding.isSummary) {
            missedIssues.push(finding);
        }
    });

    return { missedIssues };
}

/**
 * Find issues both AIs agree on
 */
function findCommonIssues(sparkResult, irisResult) {
    const common = [];

    sparkResult.findings.forEach(sparkFinding => {
        const matchInIris = irisResult.findings.find(irisFinding =>
            areFindingsSimilar(sparkFinding.description, irisFinding.description)
        );

        if (matchInIris && !sparkFinding.isSummary) {
            common.push(sparkFinding);
        }
    });

    return common;
}

/**
 * Compare findings from both AIs and create unified report
 */
function compareFindingsAndMerge(sparkResult, irisResult, originalQuery, dialogue = null) {
    const confirmedByBoth = [];
    const sparkOnly = [];
    const irisOnly = [];
    const allIssues = new Set();

    // Categorize findings
    sparkResult.findings.forEach(sparkFinding => {
        const matchInIris = irisResult.findings.find(irisFinding =>
            areFindingsSimilar(sparkFinding.description, irisFinding.description)
        );

        if (matchInIris) {
            confirmedByBoth.push({
                description: sparkFinding.description,
                type: sparkFinding.type,
                confidence: 'high', // Both AIs agree
                sources: ['SPARK', 'IRIS'],
            });
            allIssues.add(sparkFinding.description.toLowerCase());
        } else {
            sparkOnly.push(sparkFinding);
            allIssues.add(sparkFinding.description.toLowerCase());
        }
    });

    irisResult.findings.forEach(irisFinding => {
        const alreadyConfirmed = confirmedByBoth.some(confirmed =>
            areFindingsSimilar(confirmed.description, irisFinding.description)
        );

        if (!alreadyConfirmed) {
            irisOnly.push(irisFinding);
            allIssues.add(irisFinding.description.toLowerCase());
        }
    });

    // Build unified report
    const disagreementTracker = buildDisagreementTracker(sparkOnly, irisOnly, dialogue);

    const report = buildUnifiedReport({
        confirmedByBoth,
        sparkOnly,
        irisOnly,
        sparkRaw: sparkResult.rawResponse,
        irisRaw: irisResult.rawResponse,
        originalQuery,
        disagreementTracker,
    });

    return {
        unifiedReport: report,
        confirmedByBoth,
        sparkOnly,
        irisOnly,
        totalIssuesFound: allIssues.size,
        disagreementTracker,
        sparkResult,
        irisResult,
    };
}

function buildDisagreementTracker(sparkOnly, irisOnly, dialogue = []) {
    const unresolved = [];

    sparkOnly.forEach(finding => {
        unresolved.push({
            source: 'SPARK',
            description: finding.description,
            type: finding.type,
            status: 'unresolved',
        });
    });

    irisOnly.forEach(finding => {
        unresolved.push({
            source: 'IRIS',
            description: finding.description,
            type: finding.type,
            status: 'unresolved',
        });
    });

    const disagreementKeywords = ['disagree', 'different', 'not sure', 'uncertain', 'conflict', 'doesn\'t match', 'does not match'];
    const dialogueSignals = dialogue
        .filter(entry => typeof entry.message === 'string')
        .filter(entry => disagreementKeywords.some(keyword => entry.message.toLowerCase().includes(keyword)))
        .slice(-6)
        .map(entry => ({
            source: entry.role,
            description: entry.message.slice(0, 180),
            type: 'discussion',
            status: 'needs-review',
        }));

    const combined = [...unresolved, ...dialogueSignals];
    const deduped = [];
    combined.forEach(item => {
        const exists = deduped.some(existing => areFindingsSimilar(existing.description, item.description));
        if (!exists) deduped.push(item);
    });

    return {
        unresolvedItems: deduped,
        unresolvedCount: deduped.length,
    };
}

/**
 * Check if two findings are describing the same issue
 */
function areFindingsSimilar(finding1, finding2) {
    const normalize = (str) => str.toLowerCase().replace(/[^\w\s]/g, '').trim();
    const f1 = normalize(finding1);
    const f2 = normalize(finding2);

    // Check for exact match
    if (f1 === f2) return true;

    // Check for substantial overlap
    const words1 = new Set(f1.split(/\s+/));
    const words2 = new Set(f2.split(/\s+/));
    const commonWords = [...words1].filter(w => words2.has(w) && w.length > 3);

    // If >60% of meaningful words overlap, consider similar
    const overlapRatio = commonWords.length / Math.min(words1.size, words2.size);
    return overlapRatio > 0.6;
}

/**
 * Build formatted unified diagnostic report
 */
function buildUnifiedReport({ confirmedByBoth, sparkOnly, irisOnly, sparkRaw, irisRaw, originalQuery, disagreementTracker }) {
    let report = `# 🤝 Collaborative Diagnostic Report\n\n`;
    report += `**Question:** ${originalQuery}\n\n`;
    report += `**S.P.A.R.K and I.R.I.S analyzed this problem independently, then compared findings.**\n\n`;
    report += `---\n\n`;

    // Confirmed by both
    if (confirmedByBoth.length > 0) {
        report += `## ✅ Confirmed by Both AIs (High Confidence)\n\n`;
        confirmedByBoth.forEach((finding, i) => {
            report += `${i + 1}. **${finding.description}**\n`;
        });
        report += `\n`;
    }

    // S.P.A.R.K unique findings
    if (sparkOnly.length > 0) {
        report += `## 🔵 Additional Issues Found by S.P.A.R.K\n\n`;
        sparkOnly.forEach((finding, i) => {
            const icon = finding.type === 'error' ? '❌' : finding.type === 'warning' ? '⚠️' : '💡';
            report += `${i + 1}. ${icon} ${finding.description}\n`;
        });
        report += `\n`;
    }

    // I.R.I.S unique findings
    if (irisOnly.length > 0) {
        report += `## 🟣 Additional Issues Found by I.R.I.S\n\n`;
        irisOnly.forEach((finding, i) => {
            const icon = finding.type === 'error' ? '❌' : finding.type === 'warning' ? '⚠️' : '💡';
            report += `${i + 1}. ${icon} ${finding.description}\n`;
        });
        report += `\n`;
    }

    // Combined recommendations
    report += `---\n\n`;
    report += `## 📋 Combined Action Plan\n\n`;

    const allFindings = [...confirmedByBoth, ...sparkOnly, ...irisOnly];
    const errors = allFindings.filter(f => f.type === 'error');
    const warnings = allFindings.filter(f => f.type === 'warning');
    const fixes = allFindings.filter(f => f.type === 'fix');

    if (errors.length > 0) {
        report += `### Priority 1: Critical Issues\n`;
        errors.slice(0, 3).forEach((f, i) => {
            report += `${i + 1}. ${f.description}\n`;
        });
        report += `\n`;
    }

    if (warnings.length > 0) {
        report += `### Priority 2: Warnings\n`;
        warnings.slice(0, 3).forEach((f, i) => {
            report += `${i + 1}. ${f.description}\n`;
        });
        report += `\n`;
    }

    if (fixes.length > 0) {
        report += `### Recommended Fixes\n`;
        fixes.slice(0, 5).forEach((f, i) => {
            report += `${i + 1}. ${f.description}\n`;
        });
        report += `\n`;
    }

    if (disagreementTracker?.unresolvedCount > 0) {
        report += `### Disagreement Tracker (Needs Review)\n`;
        disagreementTracker.unresolvedItems.slice(0, 8).forEach((item, i) => {
            report += `${i + 1}. [${item.source}] ${item.description}\n`;
        });
        report += `\n`;
    }

    report += `---\n\n`;
    report += `💭 **Analysis Notes:**\n`;
    report += `- Both AIs reviewed the same data independently\n`;
    report += `- Items confirmed by both have higher confidence\n`;
    report += `- Unique findings from each AI provide additional perspectives\n`;
    report += `- Start with Priority 1 issues first\n`;

    return report;
}

export default {
    runParallelDiagnostics,
    compareFindingsAndMerge,
};
